### ISSUE TITLE
generator overwrites files it created

### ISSUE THREAD

**Issue by mortona42** [forumone/generator-web-starter#11]
I'm not sure if this is avoidable, but the generator prompts you to overwrite files that were created by the generator.

From Drupal generator:
>   create puppet/shell/pre-provision.sh
>identical Gemfile
>identical Gruntfile.js
> conflict package.json
>? Overwrite package.json? overwrite
>    force package.json
>   create config/deploy.rb

From WordPress generator:
> conflict Gemfile
>? Overwrite Gemfile? overwrite
>    force Gemfile
> conflict Gruntfile.js
>? Overwrite Gruntfile.js? overwrite
>    force Gruntfile.js
> conflict package.json
>? Overwrite package.json? overwrite
>    force package.json

**Comment by slucero** [comment]
Without more context for your specific use case, you might be seeing part of the update process for the generator. One of the features is being able to run the generator on an existing project and pull in updated dependencies and configuration. During this process it tries to walk you through files with changes to help with conflict resolution in order to avoid unexpectedly blowing away some of your project-specific customizations.

Related:
* #16

**Comment by azinck** [comment]
I got these exact same errors when running the generator on a brand-new, completely empty repo.  So it definitely doesn't have anything to do with updating an existing project.

**Comment by wwhurley** [comment]
It happens because the web-starter repo contains some files that are then created from the template. So the repo is cloned into the yeoman cache, copied over, and then each of the templates are evaluated. Since things like package.json, etc. are in the repo and are different from what comes out of the template yeoman verifies that you intend the change. The solution to this would be to remove the non-templated version from the repo, though that would have the effect of making the clone-and-go method of starting a project somewhat more difficult.
